# Generated by Django 4.2.8 on 2023-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productid',
            field=models.IntegerField(null=True),
        ),
    ]
