# Generated by Django 4.2.8 on 2023-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_category',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(default='vd', upload_to='cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='dc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.CharField(default=44, max_length=20),
            preserve_default=False,
        ),
    ]
