# Generated by Django 4.2.8 on 2023-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_product_category_cart_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='parcel',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
