# Generated by Django 4.2.8 on 2023-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orders_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='productid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
