# Generated by Django 4.2.8 on 2024-01-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_orders_status_completedorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorders',
            name='productid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='productid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
