# Generated by Django 4.2.8 on 2024-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_completedorders_productid_orders_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='keysecret',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='rkeyid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
