# Generated by Django 4.2.8 on 2024-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_store_keysecret_store_rkeyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='parcel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
