# Generated by Django 4.2.8 on 2024-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orders_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='parcel',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
