# Generated by Django 4.2.8 on 2024-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_orders_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
