# Generated by Django 4.2.8 on 2024-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_store_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
