# Generated by Django 4.2.8 on 2024-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_feed_mail_feedback_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordernumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
