# Generated by Django 4.2.8 on 2024-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_orders_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_city',
            new_name='store_address',
        ),
    ]
