# Generated by Django 4.2.8 on 2024-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_completedorders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
