# Generated by Django 4.2.8 on 2024-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_store_store_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_timings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orderid',
            field=models.IntegerField(),
        ),
    ]
